resources:
  - name: kayhut_script
    type: GitRepo
    configuration:
      gitProvider: github       
      path: DekelMalul/kayhut-script  
     
      
pipelines:
  - name: build_image
    steps:
      - name: build
        type: DockerBuild 
        configuration:
          inputResources:
            - name: kayhut_script
          dockerFileLocation: dockerfile/
          dockerFileName: dockerfile
          dockerImageName: strupper
          dockerImageTag: latest
