FROM python:3-alpine
WORKDIR /root
COPY .pip /root/.pip
RUN apk add git && git clone https://github.com/DekelMalul/kayhut-script.git && pip install strupper
WORKDIR /root/globaldots-script
CMD python app.py dekel
